app/models.py
from app import app
from app import db


class IPWhitelist(db.Model):
    __tablename__ = "ip_whitelist"

    id            = db.Column(db.Integer(), primary_key=True)
    cidr_ip       = db.Column(db.String())
    description   = db.Column(db.Text())
 
    def __init__(self, cidr_ip, description):
        self.cidr_ip       = cidr_ip
        self.description   = description

app/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.httpauth import HTTPBasicAuth
from flask.ext.mail import Mail
from flask.ext.cache import Cache
import os
import yaml

app = Flask(__name__)
app.secret_key = 'SUPERSECRET' # you should change this to something equally random
app.config['CONFIG_FILE'] = os.path.abspath('app/config.yaml')
configStr = open(app.config['CONFIG_FILE'], 'r')
app.config['CONFIG'] = yaml.load(configStr)
sqlite_db = os.path.abspath('db/elastatus.db')
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////%s' % sqlite_db

# Allow arbitrary python code in Jinja templates
app.jinja_options['extensions'].append('jinja2.ext.do')

db = SQLAlchemy(app)
auth = HTTPBasicAuth()
mail = Mail(app)
cache = Cache()
cache.init_app(app, config={'CACHE_TYPE': 'simple',
                            'CACHE_DEFAULT_TIMEOUT':app.config['CONFIG']['sgaudit']['cache_timeout']
                            })

if app.config['CONFIG']['jobs']['enabled']:
    from jobs import *


from app.models import *

@app.before_first_request
def create_db():
    if not os.path.exists(sqlite_db):
        db.create_all()


from views import elastatus as elastatus
from api import api as api
from admin import admin as admin
app.register_blueprint(elastatus)
app.register_blueprint(api, url_prefix='/api')
app.register_blueprint(admin, url_prefix='/admin')

app/views.py
from flask import *
import os
from pprint import pprint
from decorators import validate_account_and_region
from aws import connect, r53
from sgaudit import get_reports, add_description
from app.models import IPWhitelist

elastatus  = Blueprint('elastatus', __name__)


@elastatus.route('/')
def index():
    default_account = current_app.config['CONFIG']['default_account']
    default_region  = current_app.config['CONFIG']['default_region']
    default_service = current_app.config['CONFIG']['default_service']
    return redirect(url_for('.'+default_service, account=default_account, region=default_region))


@elastatus.route('/<account>/<region>/ec2')
@validate_account_and_region
def ec2(account, region):
    c = connect(account, region, 'ec2')
    instances = c.describe_instances()
    return render_template('ec2.html', region=region, instances=instances)

@elastatus.route('/<account>/<region>/ami')
@validate_account_and_region
def ami(account, region):
    c = connect(account,region, 'ec2')
    amis = c.describe_images(Owners=['self'])
    return render_template('ami.html', region=region, amis=amis)


@elastatus.route('/<account>/<region>/ebs')
@validate_account_and_region
def ebs(account, region):
    c = connect(account, region, 'ec2')
    volumes = c.describe_volumes()
    return render_template('ebs.html', volumes=volumes)


@elastatus.route('/<account>/<region>/snapshots')
@validate_account_and_region
def snapshots(account, region):
    c = connect(account, region, 'ec2')
    snapshots = c.describe_snapshots(OwnerIds=['self'])
    return render_template('snapshots.html', region=region, snapshots=snapshots)


@elastatus.route('/<account>/<region>/autoscale')
@validate_account_and_region
def autoscale(account, region):
    c = connect(account, region, 'autoscale')
    asg = c.describe_auto_scaling_groups()
    pprint(asg)
    return render_template('asg.html', region=region, asg=asg)


@elastatus.route('/<account>/<region>/elb')
@validate_account_and_region
def elb(account, region):
    c = connect(account, region, 'elb')
    elb = c.get_all_load_balancers()
    return render_template('elb.html', region=region, elb=elb)


@elastatus.route('/<account>/<region>/sg/<id>')
@validate_account_and_region
def sg(account, region, id):
    c = connect(account, region,'ec2')
    sg = c.get_all_security_groups(filters={'group-id': id})
    sg = add_description(sg)
    return render_template('sg.html', region=region, sg=sg)


@elastatus.route('/<account>/<region>/elasticache')
@validate_account_and_region
def elasticache(account, region):
    c = connect(account, region, 'elasticache')
    clusters = c.describe_cache_clusters(ShowCacheNodeInfo=True)
    pprint(clusters)
    return render_template('elasticache.html', clusters=clusters)


@elastatus.route('/<account>/<region>/route53')
def route53(account, region):
    c, domain, zone_id = r53()
    r = list()
    try:
        records = c.get_all_rrsets(zone_id)
        paginate = True
        while paginate:
            for item in records:
                r.append(item)
            paginate = records.next_token
    except:
        domain = None
    return render_template('r53.html', domain=domain, records=r)


@elastatus.route('/<account>/<region>/rds')
def rds(account, region):
    c = connect(account, region, 'rds')
    db_instances = c.describe_db_instances()
    return render_template('rds.html', db_instances=db_instances)


@elastatus.route('/<account>/<region>/dynamodb')
def dynamodb(account, region):
    c = connect(account, region, 'dynamodb')
    tables = c.list_tables()
    if tables:
        tables = [c.describe_table(TableName=x) for x in tables['TableNames']]
    else:
        tables = list()
    return render_template('dynamodb.html', tables=tables)


@elastatus.route('/<account>/<region>/cloudformation')
def cloudformation(account, region):
    c = connect(account, region, 'cloudformation')
    stacks = c.describe_stacks()
    return render_template('cloudformation.html', stacks=stacks)


@elastatus.route('/<account>/<region>/cloudformation/<stack_name>.json')
def get_template(account, region, stack_name):
    c = connect(account, region, 'cloudformation')
    template = c.get_template(stack_name)
    template = template["GetTemplateResponse"]["GetTemplateResult"]["TemplateBody"]
    response = make_response(template)
    response.headers["Content-Disposition"] = "attachment; filename=%s.json" % stack_name
    return response


@elastatus.route('/<account>/<region>/cloudwatch')
def cloudwatch(account, region):
    return render_template('cloudwatch.html')


@elastatus.route('/<account>/<region>/sns')
def sns(account, region):
    c = connect(account, region, 'sns')
    subscriptions = c.get_all_subscriptions()
    subscriptions = subscriptions['ListSubscriptionsResponse']['ListSubscriptionsResult']['Subscriptions']
    return render_template('sns.html', subscriptions=subscriptions)


@elastatus.route('/<account>/<region>/redshift')
def redshift(account, region):
    c = connect(account, region, 'redshift')
    clusters = c.describe_clusters()
    clusters = clusters['DescribeClustersResponse']['DescribeClustersResult']['Clusters']
    return render_template('redshift.html', clusters=clusters)


@elastatus.route('/<account>/<region>/sqs')
def sqs(account, region):
    c = connect(account, region, 'sqs')
    queues = list()
    all_queues = c.get_all_queues()
    for q in all_queues:
        url = 'https://sqs.%s.amazonaws.com%s' % (region, q.id)
        attributes = q.get_attributes()
        attributes['url'] = url
        queues.append(attributes)
    return render_template('sqs.html', queues=queues)


@elastatus.route('/<account>/<region>/sgaudit')
def sgaudit(account, region):
    c = connect(account, region, 'ec2')
    report, empty_groups = get_reports(c)
    return render_template('sgaudit.html', report=report)

app/templates/admin.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />

        <title>Elastatus Admin</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <style type="text/css">
          body {
           padding-top: 60px;
           padding-bottom: 40px;
        }
        </style>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-responsive.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/DT_bootstrap.css') }}">
        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script>

        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/jquery.dataTables.js') }}"></script>
        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/DT_bootstrap.js') }}"></script>

    </head>
    <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{{ url_for('elastatus.index') }}">Elastatus</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="{{ url_for('.index') }}"><i class="icon-wrench icon-white"></i> Admin</a></li>
              <li><a href="{{ url_for('elastatus.index') }}">Home <i class="icon-arrow-left icon-white"></i></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    {% block content %}
    {% endblock %}

  </body>
</html>

app/templates/ami.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/ec2.png') }}"> Elastic Cloud Compute - Images</h2>

    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>Name</th>
	    <th>AMI ID</th>
	    <th>Status</th>
            <th>Public</th>
            <th>Root Device</th>
            <th>Virt Type</th>
            <th>Tags</th>
            <th>Created</th>
        </tr>
    </thead>
    <tbody>
        {% for ami in amis['Images'] %}
        <tr>
            <td>{{ami.Name}}</td>
            <td>{{ami.ImageId}}</td>
            <td>{{ami.State}}</td>
            <td>{{ami.Public}}</td>
            <td>{{ami.RootDeviceType}}</td>
            <td>{{ami.RootDeviceName}}</td>
            <td>{% for tag in ami.BlockDeviceMappings %} <br> {% endfor %}
            <td>{{ami.CreationDate}}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}

app/templates/cloudformation.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/cloudformation.png') }}"> AWS CloudFormation</h2>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>Name</th>
            <th>Created</th>
            <th>Status</th>
            <th>Status Timestamp</th>
            <th>Resources</th>
            <th>Template</th>
        </tr>
    </thead>
    <tbody>
        {% for s in stacks %}
        <tr>
            <td>{{ s.stack_name}}</td>
            <td>{{ s.creation_time.strftime('%Y-%m-%d %H:%M:%S') }}</td>
            <td>{{ s.stack_status }}</a></td>
            <td>{{ s.describe_events()[0].timestamp.strftime('%Y-%m-%d %H:%M:%S') }}</td>
            <td>{% for r in s.describe_resources() %}
                {{ r }}<br>
                {% endfor %}
            </td>
            <td>
              <a class="btn btn-info" type="button" href="{{ url_for('.get_template', account=current_account, region=current_region, stack_name=s.stack_name)}}"><i class="icon-download-alt icon-white"></i> Download Template</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

app/templates/cloudwatch.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/cloudwatch.png') }}"> AWS CloudWatch</h2>

{% endblock %}

app/templates/dynamodb.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/dynamodb.png') }}"> DynamoDB</h2>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>Name</td>
            <th>Reads</th>
            <th>Writes</th>
            <th>Size in Bytes</th>
            <th>Key Schema</th>
            <th>Item Count</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for t in tables %}
        <tr>
            <td>{{ t.Table.TableName }}</td>
            <td>{{ t.Table.ProvisionedThroughput.ReadCapacityUnits }}</td>
            <td>{{ t.Table.ProvisionedThroughput.WriteCapacityUnits }}</td>
            <td>{{ t.Table.TableSizeBytes }}</td>
            <td>{% set schema = t.Table.KeySchema %}
                {% for i in schema %}
                {{ schema.KeyType }} : {{ schema.AttributeName }}<br>
                {% endfor %}</td>
            <td>{{ t.Table.ItemCount }}</td>
            <td>{{ t.Table.TableStatus }}</td>   
        </tr>
        {% endfor %}
    </tbody>
    </table>      
{% endblock %}

app/templates/ebs.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/ebs.png') }}"> Elastic Block Storage</h2>

    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>Name</th>
            <th>ID</th>
            <th>Size GB</th>
            <th>IOPS</th>
            <th>Attachment State</th>
            <th>Zone</th>
            <th>Status</th>
            <th>Created</th>
        </tr>
    </thead>
    <tbody>
        {% for v in volumes['Volumes'] %}
        <tr>
            <td>{{ v.VolumeType }}</td>
            <td>{{ v.VolumeId }}</td>
            <td>{{ v.Size }}
            <td>{{ v.Iops }}</td>
            <td>{% for group in v.Attachments %}
                {{ group.Device }}:{{ group.State }}<br>
            {% endfor %}</td>
            <td>{{ v.AvailabilityZone }}</td>
            <td>{{ v.State }}</td>
            <td>{{ v.CreateTime }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>      
</div>
{% endblock %}

app/templates/elasticache.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/elasticache.png') }}"> Elasticache</h2>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>CacheClusterId</th>
            <th>Engine</th>
            <th>Address</th>
            <th>Port</th>
            <th>Nodes</th>
            <th>Zone</th>
            <th>Groups</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for cluster in clusters.CacheClusters %}
        <tr>
            <td>{{ cluster['CacheClusterId'] }}</td>
            <td>{{ cluster['Engine'] }}</td>
            {% if cluster['Engine'] == 'memcached' %}
                <td>{{ cluster['ConfigurationEndpoint']['Address'] }}</td>
                <td>{{ cluster['ConfigurationEndpoint']['Port'] }}</td>
            {% elif cluster['Engine'] == 'redis' %}
                {% for nodes in cluster['CacheNodes'] %}
                    <td>{{ nodes['Endpoint']['Address'] }}</td>
                    <td>{{ nodes['Endpoint']['Port'] }}</td>
                {% endfor %}
            {% endif %}
            <td>{{ cluster['NumCacheNodes'] }}</td>
            <td>{{ cluster['PreferredAvailabilityZone'] }}</td>
            {% if cluster['CacheSecurityGroups'] == None %}
            <td></td>
            {% else %}
            <td><a href="{{ url_for('.sg', account=current_account, region=region, id=cluster['SecurityGroups'][0]['SecurityGroupId']) }}">{{cluster['SecurityGroups'][0]['SecurityGroupId']}}</a></td>
            {% endif %}
            <td>{{ cluster['CacheClusterStatus'] }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}

app/templates/elb.html
{% extends "layout.html" %}
{% block content %}
   <div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/elb.png') }}"> Elastic Load Balancers</h2>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>Name</th>
            <th>Listeners</th>
            <th>Instances</th>
            <th>Security Groups</th>
            <th>Healthcheck</th>
        </tr>
    </thead>
    <tbody>
        {% for lb in elb %}
        <tr>
            <td>{{ lb.dns_name }}</td>
            <td>{% for i in lb.listeners %}
                In: {{ i[0] }}, Out: {{ i[1] }}, {{ i[2] }}<br>
                {% endfor %}</td>
            <td>{% for i in lb.instances %}
                {{ i.id }}<br>
                {% endfor %}</td>
            <td>{% for i in lb.security_groups %}
                <a href="{{ url_for('.sg', account=current_account, region=current_region, id=i) }}">{{ i }}<br>
                {% endfor %}</td>
            <td>{{ lb.health_check }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />

        <title>Elastatus</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <style type="text/css">
          body {
           padding-top: 60px;
           padding-bottom: 40px;
        }
        </style>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-responsive.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/DT_bootstrap.css') }}">
        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script>

        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/jquery.dataTables.js') }}"></script>
        <script type="text/javascript" charset="utf-8" language="javascript" src="{{ url_for('static', filename='js/DT_bootstrap.js') }}"></script>

    </head>
    <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{{ url_for('elastatus.index') }}">Elastatus</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-tasks icon-white"></i>
                  {% set current_account = request.view_args.get('account') %}
                  {% set current_region = request.view_args.get('region') %}
                  {% set current_service = request.url_rule.rule.split('/')[3] %}
                  {% if current_account == '' %}
                  Accounts
                  {% elif config['CONFIG']['accounts'].has_key(current_account) %}
                  {{ current_account.capitalize() }}
                  {% else %}
                  Accounts
                  {% endif %} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                {% for account in config['CONFIG']['accounts'] %}
                  {% if current_service == 'sg' %}
                  <li><a href="{{ url_for('elastatus.ec2', account=current_account, region=current_region) }}">{{ account.capitalize() }}</a></li>
                  {% else %}
                  {% set args = request.view_args.copy() %}
                  {% do args.update({'account': account}) %}
                  <li><a href="{{ url_for('elastatus.'+current_service, **args) }}">{{ account.capitalize() }}</a></li>
                  {% endif %}
                {% endfor %}
                </ul>
              </li>
              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-globe icon-white"></i>
                  {{ current_region }} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                {% for region in config['CONFIG']['regions'] %}
                  {% if current_service == 'sg' %}
                  <li><a href="{{ url_for('elastatus.ec2', account=current_account, region=current_region) }}">{{ region }}</a></li>
                  {% else %}
                  {% set args = request.view_args.copy() %}
                  {% do args.update({'region': region}) %}
                  <li><a href="{{ url_for('elastatus.'+current_service, **args) }}">{{ region }}</a></li>
                  {% endif %}
                {% endfor %}
                </ul>
              </li>

              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-hdd icon-white"></i>
                  Compute<b class="caret"></b></a>
                <ul class="dropdown-menu">
                {% for service in config['CONFIG']['aws']['compute'] %}
                  <li><a href="{{ url_for('elastatus.'+service, account=current_account, region=current_region) }}">{{ service.upper() }}</a></li>
                {% endfor %}
                </ul>
              </li>

              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-tasks icon-white"></i>
                  Database<b class="caret"></b></a>
                <ul class="dropdown-menu">
                {% for service in config['CONFIG']['aws']['database'] %}
                  <li><a href="{{ url_for('elastatus.'+service, account=current_account, region=current_region) }}">{{ service.upper() }}</a></li>
                {% endfor %}
                </ul>
              </li>

              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-inbox icon-white"></i>
                  App Services<b class="caret"></b></a>
                <ul class="dropdown-menu">
                {% for service in config['CONFIG']['aws']['services'] %}
                  <li>
                    {% if service == "route53" %}
                    <a href="{{ url_for('elastatus.'+service, account=config['CONFIG']['route53']['account'], region=current_region) }}">{{ service.upper() }}</a></li>
                    {% else %}
                    <a href="{{ url_for('elastatus.'+service, account=current_account, region=current_region) }}">{{ service.upper() }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
              </li>

              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-tags icon-white"></i>
                  Deployments<b class="caret"></b></a>
                <ul class="dropdown-menu">
                {% for service in config['CONFIG']['aws']['deployments'] %}
                  <li><a href="{{ url_for('elastatus.'+service, account=current_account, region=current_region) }}">{{ service.upper() }}</a></li>
                {% endfor %}
                </ul>
              </li>

              {% if request.blueprint == 'admin' %}
                <li class="active">
              {% else %}
                <li>
              {% endif %}
              <a href="{{ url_for('admin.index') }}"><i class="icon-wrench icon-white"></i> Admin</a>
            </li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    {% block content %}
    {% endblock %}

  </body>
</html>

app/templates/r53.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/route53.png') }}"> Amazon Route53</h2>
    <h3>{{ domain }}</h3>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>Name</th>
            <th>Record</th>
            <th>Type</th>
            <th>TTL</th>
        </tr>
    </thead>
    <tbody>
        {% for record in records %}
        <tr>
            <td>{{ record.name }}</td>
            <td>{% for i in record.resource_records %}
                {{ i }}<br>
                {% endfor %}</td>
            <td>{{ record.type }}</td>
            <td>{{ record.ttl }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>      
</div>
{% endblock %}

app/templates/rds.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/rds.png') }}"> Relational Database Service</h2>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>ID</th>
            <th>Hostname</th>
            <th>Port</th>
            <th>Engine</th>
            <th>Storage</th>
            <th>Zone</th>
            <th>Multi-AZ</th>
            <th>IOPs</th>
            <th>Groups</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for db in db_instances.DBInstances %}
        <tr>
            <td>{{ db.DBInstanceIdentifier }}</td>
            <td>{{ db.Endpoint.Address }}</a></td>
            <td>{{ db.Endpoint.Port }}</td>
            <td>{{ db.Engine }}</td>
            <td>{{ db.AllocatedStorage }}</td>
            <td>{{ db.AvailabilityZone }}</td>
            <td>{{ db.MultiAZ }}</td>
            <td>{{ db.Iops }}</td>
            <td>{% for group in db.VpcSecurityGroups %}
                <a href="{{ url_for('.sg', account=current_account, region=current_region, id=group.vpc_group) }}">{{ group.vpc_group }}</a><br>
            {% endfor %}</td>
            <td>{{ db.DBInstanceStatus }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}

app/templates/sns.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <h2><img src="{{ url_for('static', filename='img/aws/sns.png') }}"> Simple Notification Service</h2>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="info">
    <thead>
        <tr>
            <th>Subscription ID</td>
            <th>Protocol</th>
            <th>Endpoint</th>
            <th>TopicArn</th>
        </tr>
    </thead>
    <tbody>
        {% for s in subscriptions %}
        <tr>
            <td>{{ s.SubscriptionArn }}</td>
            <td>{{ s.Protocol }}</td>
            <td>{{ s.Endpoint }}</td>
            <td>{{ s.TopicArn }}</td>            
        </tr>
        {% endfor %}
    </tbody>
    </table>      
{% endblock %}